export interface UseBreakpointMediaQuery {
    '-d': string
    '-d+': string
    '-d-': string
    '-device': string
    '-device+': string
    '-device-': string
    '-l': string
    '-l+': string
    '-l-': string
    '-large': string
    '-large+': string
    '-large-': string
    '-m': string
    '-m+': string
    '-m-': string
    '-med': string
    '-med+': string
    '-med-': string
    '-medium': string
    '-medium+': string
    '-medium-': string
    '-mi': string
    '-mi+': string
    '-mi-': string
    '-micro': string
    '-micro+': string
    '-micro-': string
    '-mobile': string
    '-mobile+': string
    '-mobile-': string
    '-s': string
    '-s+': string
    '-s-': string
    '-sd': string
    '-sd+': string
    '-sd-': string
    '-small': string
    '-small+': string
    '-small-': string
    '-smallDevice': string
    '-smallDevice+': string
    '-smallDevice-': string
    '-t': string
    '-t+': string
    '-t-': string
    '-tablet': string
    '-tablet+': string
    '-tablet-': string
    d: string
    'd+': string
    'd-': string
    device: string
    'device+': string
    'device-': string
    l: string
    'l+': string
    'l-': string
    large: string
    'large+': string
    'large-': string
    m: string
    'm+': string
    'm-': string
    med: string
    'med+': string
    'med-': string
    medium: string
    'medium+': string
    'medium-': string
    mi: string
    'mi+': string
    'mi-': string
    micro: string
    'micro+': string
    'micro-': string
    mobile: string
    'mobile+': string
    'mobile-': string
    s: string
    's+': string
    's-': string
    sd: string
    'sd+': string
    'sd-': string
    small: string
    'small+': string
    'small-': string
    smallDevice: string
    'smallDevice+': string
    'smallDevice-': string
    t: string
    't+': string
    't-': string
    tablet: string
    'tablet+': string
    'tablet-': string
    '|d': string
    '|d+': string
    '|d-': string
    '|device': string
    '|device+': string
    '|device-': string
    '|l': string
    '|l+': string
    '|l-': string
    '|large': string
    '|large+': string
    '|large-': string
    '|m': string
    '|m+': string
    '|m-': string
    '|med': string
    '|med+': string
    '|med-': string
    '|medium': string
    '|medium+': string
    '|medium-': string
    '|mi': string
    '|mi+': string
    '|mi-': string
    '|micro': string
    '|micro+': string
    '|micro-': string
    '|mobile': string
    '|mobile+': string
    '|mobile-': string
    '|s': string
    '|s+': string
    '|s-': string
    '|sd': string
    '|sd+': string
    '|sd-': string
    '|small': string
    '|small+': string
    '|small-': string
    '|smallDevice': string
    '|smallDevice+': string
    '|smallDevice-': string
    '|t': string
    '|t+': string
    '|t-': string
    '|tablet': string
    '|tablet+': string
    '|tablet-': string
}
export interface UseBreakpoint {
    innerHeight: number
    innerWidth: number
    'is-D': boolean
    'is-D+': boolean
    'is-D-': boolean
    'is-Device': boolean
    'is-Device+': boolean
    'is-Device-': boolean
    'is-L': boolean
    'is-L+': boolean
    'is-L-': boolean
    'is-Large': boolean
    'is-Large+': boolean
    'is-Large-': boolean
    'is-M': boolean
    'is-M+': boolean
    'is-M-': boolean
    'is-Med': boolean
    'is-Med+': boolean
    'is-Med-': boolean
    'is-Medium': boolean
    'is-Medium+': boolean
    'is-Medium-': boolean
    'is-Mi': boolean
    'is-Mi+': boolean
    'is-Mi-': boolean
    'is-Micro': boolean
    'is-Micro+': boolean
    'is-Micro-': boolean
    'is-Mobile': boolean
    'is-Mobile+': boolean
    'is-Mobile-': boolean
    'is-S': boolean
    'is-S+': boolean
    'is-S-': boolean
    'is-Sd': boolean
    'is-Sd+': boolean
    'is-Sd-': boolean
    'is-Small': boolean
    'is-Small+': boolean
    'is-Small-': boolean
    'is-SmallDevice': boolean
    'is-SmallDevice+': boolean
    'is-SmallDevice-': boolean
    'is-T': boolean
    'is-T+': boolean
    'is-T-': boolean
    'is-Tablet': boolean
    'is-Tablet+': boolean
    'is-Tablet-': boolean
    'isD+': boolean
    'isD-': boolean
    isDevice: boolean
    'isDevice+': boolean
    'isDevice-': boolean
    isDundefined: boolean
    isHDPI: boolean
    'isL+': boolean
    'isL-': boolean
    isLandscape: boolean
    isLarge: boolean
    'isLarge+': boolean
    'isLarge-': boolean
    isLundefined: boolean
    'isM+': boolean
    'isM-': boolean
    isMed: boolean
    'isMed+': boolean
    'isMed-': boolean
    isMedium: boolean
    'isMedium+': boolean
    'isMedium-': boolean
    isMi: boolean
    'isMi+': boolean
    'isMi-': boolean
    isMicro: boolean
    'isMicro+': boolean
    'isMicro-': boolean
    isMobile: boolean
    'isMobile+': boolean
    'isMobile-': boolean
    isMundefined: boolean
    isPortrait: boolean
    'isS+': boolean
    'isS-': boolean
    isSd: boolean
    'isSd+': boolean
    'isSd-': boolean
    isSmall: boolean
    'isSmall+': boolean
    'isSmall-': boolean
    isSmallDevice: boolean
    'isSmallDevice+': boolean
    'isSmallDevice-': boolean
    isSundefined: boolean
    'isT+': boolean
    'isT-': boolean
    isTablet: boolean
    'isTablet+': boolean
    'isTablet-': boolean
    isTundefined: boolean
    'is|D': boolean
    'is|D+': boolean
    'is|D-': boolean
    'is|Device': boolean
    'is|Device+': boolean
    'is|Device-': boolean
    'is|L': boolean
    'is|L+': boolean
    'is|L-': boolean
    'is|Large': boolean
    'is|Large+': boolean
    'is|Large-': boolean
    'is|M': boolean
    'is|M+': boolean
    'is|M-': boolean
    'is|Med': boolean
    'is|Med+': boolean
    'is|Med-': boolean
    'is|Medium': boolean
    'is|Medium+': boolean
    'is|Medium-': boolean
    'is|Mi': boolean
    'is|Mi+': boolean
    'is|Mi-': boolean
    'is|Micro': boolean
    'is|Micro+': boolean
    'is|Micro-': boolean
    'is|Mobile': boolean
    'is|Mobile+': boolean
    'is|Mobile-': boolean
    'is|S': boolean
    'is|S+': boolean
    'is|S-': boolean
    'is|Sd': boolean
    'is|Sd+': boolean
    'is|Sd-': boolean
    'is|Small': boolean
    'is|Small+': boolean
    'is|Small-': boolean
    'is|SmallDevice': boolean
    'is|SmallDevice+': boolean
    'is|SmallDevice-': boolean
    'is|T': boolean
    'is|T+': boolean
    'is|T-': boolean
    'is|Tablet': boolean
    'is|Tablet+': boolean
    'is|Tablet-': boolean
    media: UseBreakpointMediaQuery
}
